server:
  port: 8070
spring:
  data:
    mongodb:
      username: timaslilaila
      password: 7RiZRnQZYmJOKt7u
      host: localhost
      port: 27017
      database: payment
      authentication-database: admin

application:
  config:
    users-url: http://localhost:8222/api/v1/users
    offres-url: http://localhost:8222/api/v1/offres
